Repository CA-G12/tech-quiz, pull requests merged in 2022-08, with the labels that each got.

#16 Create file structure
  .env.example
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/404.html
  public/500.html
  public/assets/error.png
  public/celebration.html
  public/css/celebration.css
  public/css/landing.css
  public/css/quiz.css
  public/css/style.css
  public/index.html
  public/javascript/scripts.js
  public/quiz.html
  public/quiz.ico
  src/__tests__/controllers.test.js
  src/app.js
  src/controllers/celebration.js
  src/controllers/index.js
  src/controllers/landing.js
  src/controllers/quiz.js
  src/errors/index.js
  src/index.js
  src/routes.js
Labels: awaiting-review

#25 6 style landing page
  public/css/landing.css
  public/index.html
Labels: approved

#24 HTML structure for landing page
  public/index.html
Labels: request-change

#31 Added the html structure for quiz page
  public/quiz.html
Labels: awaiting-review

#32 Style the quiz page
  public/css/quiz.css
  public/quiz.html
Labels: awaiting-review

#33 Fixing landing page html strucutre
  public/index.html
Labels: approved

#34 Rendering data.
  public/javascript/scripts.js
Labels: awaiting-review

#35 Added next question functionality.
  public/javascript/scripts.js
Labels: awaiting-review

#37 Setup server.
  package-lock.json
  package.json
  public/index.html
  src/app.js
  src/index.js
Labels: approved

#38 handel landing page form validation.
  public/css/landing.css
  public/index.html
  public/javascript/formValidation.js
Labels: approved

#39 Add result section to quiz page
  public/quiz.html
Labels: approved

#40 write readme file
  README.md
Labels: awaiting-review

#41 Timer function
  public/index.html
  public/javascript/scripts.js
  public/quiz.html
Labels: approved

#45 handle questions endpoint
  src/controllers/index.js
  src/controllers/questions.js
  src/routes.js
Labels: awaiting-review

#44 Error handling
  public/404.html
  public/500.html
  public/css/style.css
  src/__tests__/controllers.test.js
  src/errors/index.js
  src/routes.js
Labels: approved

#47 Fixing bugs
  public/css/quiz.css
  public/javascript/formValidation.js
  public/javascript/scripts.js
  public/quiz.html
  src/controllers/celebration.js
  src/controllers/index.js
  src/controllers/landing.js
  src/controllers/questions.js
  src/controllers/quiz.js
  src/data.json
  src/index.js
Labels: approved

#48 Deleting logs
  public/javascript/scripts.js
Labels: approved
